# Site config
baseurl: ""

# User config
title: "Virtual Fort Snelling Data"
author: "Aisos"
description: "Virtual Fort Snelling Data"
email: "aisos@umn.edu"

# User collections.
collections:
    pages:
        output: true
    tooltips:
        output: true
